### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by impress85** [m85hayashi/protospace-30550#1]
# URL
https://protospace-30550.herokuapp.com/

**Comment by tech-taro** [comment]
m85hayashiさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・プロトタイプ一覧表示機能の確認（ログアウトした状態でも、プロトタイプ一覧を閲覧できる）
→ログアウトした状態だと、ログインページにしか遷移できなかったので修正をお願いします。


必須ではありませんが、余裕があればこちらも修正し、よりクオリティの高いアプリケーションにしていただきたく存じます。（こちらは提出はしなくて大丈夫です。）
・コメント機能の確認（空のコメントでは保存されない）
→たしかに保存はされないのですが、エラー画面に遷移してしまうので余裕があれば修正をお願いします。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by impress85** [comment]
確認どうもありがとうございます。
２点修正の上、Herokuへプッシュいたしました。
お手数ですが、再度レビューお願いします。

修正点
・ログアウト状態の一覧表示
・空のコメント送信時のミス解消

**Comment by tech-taro** [comment]
m85hayashiさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by impress85** [comment]
ありがとうございます！
